version: "3.7"

services:
  node:
    command: bash -c "sleep infinity"
    build:
      context: .
      args:
        USER_UID: 1000
    environment:
      - SHELL=/bin/bash
      - MONGO_TEST_URL=mongodb://admin:mindgrep@mongodb1,mongodb2,mongodb3:27017/
    
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/test
              
    
      - MYSQL_URL=mysql://root:root@mysql:3306/test
              
      - PORT=3000
    volumes:
      - ..:/workspace/development/app:cached
      - ./scripts:/scripts
    working_dir: /workspace/development/app
    ports:
      - 3000:3000

    depends_on:


      - postgres





      - mysql





  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - postgresql-data:/var/lib/postgresql/data




  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
    - 3306:3306








volumes:


  postgresql-data:




  mysql-data:




